SELECT DISTINCT S.id_scliente,n_com,U.ID_UBIC,U.DIREC,U.CAT
FROM SUB_CLIENTE S 
	INNER JOIN SE_UBICA SE ON S.id_scliente=SE.ID_SCLIENTE
	INNER JOIN UBICACION U ON U.ID_UBIC=SE.ID_UBIC
WHERE U.CAT LIKE 'OFICINA' OR U.CAT LIKE 'OFICINA/PLANTA'
ORDER BY S.n_com


SELECT cod_con,garantia,fecha, compr
FROM CONTRATO 
where tipo like 'PREPAGO'

SELECT 
	E.*,
	C.COD_CON,
	S.n_com
FROM SUB_CLIENTE S 
	RIGHT JOIN CONTRATO C ON C.id_scliente=S.id_scliente
	RIGHT JOIN EQUIPO E ON E.COD_CON=C.cod_con
ORDER BY S.id_scliente


SELECT *
FROM EQUIPO
WHERE ubic_fis LIKE 'EN DEP%'

SELECT S.n_com,C.cod_con,C.estado
FROM SUB_CLIENTE S 
	RIGHT JOIN CONTRATO C ON C.id_scliente=S.id_scliente 


SELECT *
FROM VENTA